name: evolufy
channels:
  - defaults
  - conda-forge
  - pytorch
  # - fastai
dependencies:
  - python==3.10
  - pip
  # BASICS
  - numpy
  - scipy
  - pandas
  - pystow
  - tqdm
  - click
  - ipython
  # VISUALIZATION
  - matplotlib
  - ipympl  # interactive matplotlib plots
  - seaborn
  ## - altair
  ## - yellowbrick
  # Finance
  - yfinance
  - pyfolio-reloaded
  - zipline-reloaded
  - exchange-calendars
  - alphalens-reloaded
  - empyrical-reloaded==0.5.9
  # ML, STATS & DEEP LEARNING
  - scikit-learn
  - u8darts-all
  # - statsmodels
  # - sktime
  # - tslearn
  # - xgboost
  # - catboost
  # - lightgbm
  # - pytorch
  # - fastai  # activate fastai channel above!
  # - tensorflow
  # - keras
  # - spacy
  # OTHER TOOLS
  # - optuna
  # - dask
  # - snakeviz
  - pip:
     - -e .  # install git checkout of evolufy in editable mode
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     # - icecream
     # - jax
     # - numpyro
     # - funsor
     # - neptune-client
     # - neptune-contrib

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - jupyterlab
  - jupyter
  - dvc
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark

variables:
  ZIPLINE_ROOT: ~/playground/evolufy/data/
  QUANDL_API_KEY: irrelevant